apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-initdb
  namespace: mysql-ns
data:
  init.sql: | 
    GRANT ALL PRIVILEGES ON app_db.* TO `default`@`%`; 
    USE app_db;
    CREATE TABLE notes (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value VARCHAR(200)
    );
